version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_fast_api
    environment:
      POSTGRES_USER: library_db
      POSTGRES_PASSWORD: library_db
      POSTGRES_DB: library_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_db -d library_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      DB_USER: library_db
      DB_PASSWORD: library_db
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: library_db
    depends_on:
      postgres:
        condition: service_healthy
